name: is23am10 CI

on:
  push:
    branches:
      - main
      - "develop"
      - 'feature/*'
      - 'hotfix/*'
      - 'fix/*'
  pull_request:
    branches:
      - main
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request' 
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACTIONS_KEY }}
      - uses: actions/checkout@v3
        if: github.event_name == 'push' 
        with:
          fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACTIONS_KEY }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Create Javadoc
        run: mvn javadoc:javadoc

      - name: Pull remote
        run: |
          git pull

      - name: Generate coverage report with Jacoco
        run: mvn clean jacoco:prepare-agent install jacoco:report

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain **/jacoco.svg` ]]; then
            git config --global user.name 'mattteochen'
            git config --global user.email 'kaiximatteo.chen@mail.polimi.it'
            git add -A **/jacoco.svg
            git commit -m "[Dev] Autogenerated JaCoCo coverage badge"
            git push --force https://mattteochen:${{ secrets.BOT_ACTIONS_KEY }}@github.com/mattteochen/IS23-AM10.git
          fi
