name: is23am10 CI

on:
  push:
    branches: 
    - main
    - 'develop'
    - 'feature/jacoco'
  pull_request:
    branches:
    - main
    - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: cd is23am10/ && mvn --batch-mode --update-snapshots package

      - name: Generate coverage report with Jacoco
        run: mvn clean jacoco:prepare-agent install jacoco:report -f "/is23am10/pom.xml"
      
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true